version: '3.9'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ~/Documents/elpassion/email-survey-app/postgresql/data/:/var/lib/postgresql/data/
